import type {Metadata} from "next";
import {Geist, Geist_Mono, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import React from "react";

const jetbrainsMono = JetBrains_Mono({subsets: ['latin'], variable: '--font-mono'});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
}

export default function RootLayout(props: Readonly<Props>) {
    return (
        <html lang="en" className={cn("font-mono", jetbrainsMono.variable)}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
        >
        {props.children}
        </body>
        </html>
    );
}
